services:
  web:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    # build: .
    # depends_on:
    #   - db
    # env_file:
    #   - .env

  # db:
  #   image: mysql:5.6
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: testdb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
